remote_theme: "mmistakes/minimal-mistakes@4.28.1"

plugins:
  - jekyll-include-cache

minimal_mistakes_skin: "aqua"

title: "Maja Swieczkowska"
name: "Maja Swieczkowska"
description: "PhD Student -- KCL -- STAI CDT"

url: "https://swieczkaa.github.io/"

  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/swieczkaa"

    - label: "Google Scholar"
      icon: "fas fa-fw fa-graduation-cap"
      url: "https://scholar.google.com/citations?user=5JODjsUAAAAJ&hl=en"

    - label: "ORCID"
      icon: "fab fa-fw fa-orcid"
      url: "https://orcid.org/0009-0001-6682-7057"
