remote_theme: "mmistakes/minimal-mistakes@4.28.1"

plugins:
  - jekyll-include-cache

minimal_mistakes_skin: "aqua"

title: "Maja Swieczkowska"
name: "Maja Swieczkowska"
description: "PhD Student -- KCL -- STAI CDT"

url: "https://swieczkaa.github.io/"

